/* ============================================================
   RIVERSIDE — SZÓTÁR (felületi szövegek)

   Itt van minden GOMB, CÍMKE, ÜZENET és MENÜPONT, három nyelven:
   magyar (hu), német (de), angol (en).

   A tartalmi szövegek — házirend, gyakori kérdések, fotófeliratok,
   felszereltség — nem itt vannak, hanem a `tartalom.js` fájlban.
   Így ez a fájl rövid marad, és a hosszú szövegek egy helyen ülnek.

   HASZNÁLAT a felületen:
       const t = szoveg(nyelv);
       t.foglalas            →  'Foglalás' / 'Buchen' / 'Book'
       t.fok(3)              →  '3 fő' / '3 Personen' / '3 guests'

   ÚJ SZÖVEG FELVÉTELE: írd be mind a három nyelvhez, ugyanazzal a
   kulccsal. Ha egy nyelvből kimarad, a magyar változat jelenik meg
   helyette (lásd a fájl végén a `szoveg` függvényt), tehát az oldal
   attól még nem törik el.
   ============================================================ */

const SZOVEG = {

  /* ==========================================================
     MAGYAR
     ========================================================== */
  hu: {
    nyelvNeve: 'Magyar',
    kod: 'hu',

    /* --- Férőhely: egyetlen megfogalmazás, mindenhol ez --- */
    ferohely: (alap, pot) => alap + ' + ' + pot + ' fő',
    ferohelySugo: (alap, pot, max) => alap + ' fő az ágyakban, további ' + pot + ' a nappali kanapéján — legfeljebb ' + max + ' fő.',
    mezoVendegek: 'Vendégek',
    nincsGyerek: 'nincs gyerek',
    ugrasTartalomra: 'Ugrás a tartalomra',
    vendeghaz: 'vendégház',
    /* Kereső-leírások: ami a találati listában a cím alatt áll. */
    adatkezelesLeiras: 'Milyen adatot kérünk foglaláskor, miért kezeljük, meddig őrizzük, és kinek adjuk át. A Riverside vendégház adatkezelési tájékoztatója.',
    impresszumLeiras: 'A Riverside vendégház üzemeltetője, címe, elérhetősége és NTAK regisztrációs száma Békésszentandráson.',
    arKartyaMibe: (alap, pot) => 'a teljes házra, ' + alap + ' + ' + pot + ' főnek',
    arKartyaTol: 'ettől',

    /* --- Menü és fejléc --- */
    menuHaz: 'A ház',
    menuArak: 'Árak',
    menuGaleria: 'Galéria',
    menuKapcsolat: 'Kapcsolat',
    menuFoglalas: 'Foglalás',
    menuFoglalasom: 'Foglalásom',
    menuHazirend: 'Házirend',
    menuAdatkezeles: 'Adatkezelés',
    menuImpresszum: 'Impresszum',
    adatkezelesCim: 'Hogyan kezeljük az adataitokat.',
    impresszumCim: 'Ki üzemelteti a szálláshelyet.',
    impresszumSzallashely: 'Szálláshely',
    impresszumTarhely: 'Tárhely és üzemeltetés',
    impresszumTarhelySzoveg: 'A tárhelyszolgáltató adatai az éles indulás előtt kerülnek ide.',
    menuGomb: 'Menü',
    nyelvvalaszto: 'Nyelv',

    /* --- Általános --- */
    tovabb: 'Tovább',
    vissza: 'Vissza',
    megsem: 'Mégsem',
    bezaras: 'Bezárás',
    elozo: 'Előző',
    kovetkezo: 'Következő',
    nemKotelezo: 'nem kötelező',
    ej: 'éj',
    ejszaka: 'éjszaka',
    fok: (n) => n + ' fő',
    felnottek: (n) => n + ' felnőtt',
    gyerekek: (n) => n + ' gyerek',
    perEj: '/ éj',
    aTeljesHazra: 'a teljes házra',
    osszesen: 'Összesen',
    nincsFelar: 'nincs felár',

    /* --- Főoldal --- */
    heroFolott: 'Nyaraló a Körös holtágán',
    heroCim: 'Pár nap a víz mellett.',
    heroLead: (alap, pot) => 'Két hálószoba, nagy kert, medence, szauna és saját stég — az egész ház a tiétek, ' + alap + ' + ' + pot + ' főnek. Csendes hely — nem bulinyaraló.',
    heroGomb1: 'Foglalás',
    heroGomb2: 'A ház megtekintése',

    introFolott: 'Mi ez a hely',
    introCim: 'Holtágpart, zárt kert, 85 négyzetméter.',

    haloFolott: 'Fekvőhelyek',
    haloCim: (alap, pot) => alap + ' + ' + pot + ' személyes férőhely – a gyerekeknek is jut hely.',
    haloBevezeto: 'Két hálószoba az emeleten, a nappali kanapéját pedig kérésre ágyazzuk be. A házirend szerint legfeljebb heten lehettek.',

    velemenyFolott: 'Vendégek',
    velemenyCim: 'Amit a visszatérők mondanak.',
    velemenyDemo: 'Demóadat: ezek a szövegek a bemutatóhoz készültek, nem valódi vendégektől származnak.',

    kornyekFolott: 'Környék',
    kornyekCim: 'Ami a ház körül van.',

    gyikFolott: 'Gyakori kérdések',
    gyikCim: 'Amit a foglalás előtt meg szoktak kérdezni.',
    gyikTeljes: (link) => ['A teljes szabályzat a ', link, ' olvasható.'],
    gyikHazirendLink: 'házirendben',

    zaroCim: 'Nézd meg, mikor van hely.',
    zaroBevezeto: (ar) => ar + ' / éj-től, a teljes házra. A naptárt mi vezetjük, és 24 órán belül válaszolunk.',
    zaroGomb: 'Foglalás indítása',

    /* --- A ház oldal --- */
    hazFolott: 'A ház',
    hazCim: 'Az egész ház csak a tiétek.',
    hazMeta: (m2, halo, furdo, alap, pot) =>
      m2 + ' m² · ' + halo + ' · ' + furdo + ' fürdőszoba · ' + alap + '+' + pot + ' fő',
    hazKetHalo: 'két hálószoba és nappali',
    hazMindKep: (n) => 'Mind a ' + n + ' kép →',
    felszereltsegFolott: 'Felszereltség',
    felszereltsegCim: 'Ami a házban és a kertben van.',
    arbanFolott: 'Mi van az árban',
    arbanCim: 'És mi az, ami nincs.',
    arbanBenne: 'Benne van',
    arbanNincs: 'Nincs benne',
    kerésre: (n) => '+' + n + ' fő kérésre',

    /* --- Árak oldal --- */
    arakFolott: 'Árak',
    arakCim: 'Az ár a teljes házra szól.',
    arakBevezeto: (max) => 'A létszám nem befolyásolja a szállásdíjat — csak az idegenforgalmi adót. Legfeljebb ' + max + ' fő.',
    tablaSzezon: 'Szezon',
    tablaIdoszak: 'Időszak',
    tablaAr: 'Ár / éj',
    tablaSzabaly: 'Szabály',
    szabalyTurnus: (n) => 'pontosan ' + n + ' éj, szombat–szombat',
    szabalyMin: (n) => 'min. ' + n + ' éj',
    fizetesiFeltetelek: 'Fizetési feltételek',

    /* --- Galéria --- */
    galeriaFolott: 'Galéria',
    galeriaCim: (n) => 'Ismerd meg a házat képekben.',
    galeriaBevezeto: 'Ami a fotókon látszik, az van. A sorozat végén a földszint és az emelet 3D alaprajza is megtalálható.',
    galeriaMind: 'Mind',
    galeriaSzuresCimke: 'Fotók szűrése',
    /* A ház címkéire (medence, stég …) kattintva a galéria csak az
       adott jellemző fotóit mutatja. */
    cimkeFotok: (mi, n) => mi + ' — ' + n + ' fotó a galériában',
    /* A téli szezon a karácsonyt és az újévet is magában foglalja,
       ezért nincs külön ünnepi ár. */
    arakTelMegjegyzes: 'A téli szezon december elsejétől február végéig tart, és a karácsonyt meg az újévet is magában foglalja — ugyanazon az áron, mint a nyári főszezon.',
    galeriaCimkeSzuro: (mi) => 'Csak ezek: ' + mi,
    fotoNagyitas: 'Nagyítás',

    /* --- Foglalás --- */
    foglalasFolott: 'Foglalás',
    foglalasCim: 'Nézzük meg, mikor jönnétek.',
    lepes1: 'Időpont és vendégek',
    lepes2: 'Adatok',
    lepes3: 'Áttekintés',

    mezoIdopont: 'Időpont',
    mezoErkezes: 'Érkezés',
    mezoTavozas: 'Távozás',
    mezoFelnott: 'Felnőtt',
    mezoGyerek: 'Gyerek',
    mezoFekvohelyek: 'Fekvőhelyek',
    mezoExtrak: 'Extrák',
    mezoNev: 'Név',
    mezoEmail: 'E-mail',
    mezoTelefon: 'Telefonszám',
    mezoMegjegyzes: 'Megjegyzés',

    sugoTurnus: (n) => 'pontosan ' + n + ' éj foglalható, szombattól szombatig',
    sugoMinEj: (n) => 'min. ' + n + ' éj foglalható',
    sugoFelnott: '18 éves kor felett — utánuk jár az idegenforgalmi adó.',
    sugoGyerek: '18 év alatt, adómentes.',
    sugoExtrak: 'Bármikor módosítható, amíg nem írunk vissza.',
    sugoTelefon: 'Csak ha vissza kell hívnunk.',
    sugoMegjegyzes: 'Allergia, korai érkezés, bármi.',
    mintaNev: 'Kovács Anna',
    mintaMegjegyzes: 'Két kisgyerekkel jövünk, kutyát is hoznánk.',

    fekvohelyBevezeto: (alap, pot) => [alap + ' fő számára alapból biztosított fekvőhely', ' a két emeleti hálószobában, további ' + pot + ' fő részére a nappali kanapéja ágyként használható.'],
    kanapeCimke: 'A nappali kanapéját ágyként kérjük',
    kanapeKell: (n) => n + ' főnél ez szükséges, ezért bejelöltük.',
    kanapeNemKell: 'Ha nem kéritek, ülőgarnitúraként hagyjuk.',
    gyerekagyCimke: 'Gyermekágy a háromágyas szobába',
    gyerekagyLeiras: 'Díjmentes, és nem számít bele a férőhelybe.',
    etetoszekCimke: 'Etetőszék',
    etetoszekLeiras: 'Díjmentes, szólj előre és bekészítjük.',

    naptarSugo: 'Kattints az érkezésre, majd a távozásra',
    naptarSzabad: 'szabad',
    naptarFoglalt: 'foglalt',
    naptarKivalasztva: 'kiválasztva',
    naptarNapCimke: (nap, foglalt) => nap + (foglalt ? ' — foglalt' : ''),
    elozoHonap: 'Előző hónap',
    kovetkezoHonap: 'Következő hónap',

    altCim: 'Ekkor viszont szabad a ház',
    altHaNemJo: 'Ha egyik sem jó, írj vagy telefonálj — előfordul, hogy egy foglalás mégis felszabadul.',
    altNincs: 'A következő hónapokban nem találtunk szabad időszakot ilyen hosszra. Írj nekünk, és megnézzük, mit lehet tenni.',
    altUgyanaznap: 'ugyanezen a napon',
    altKesobb: (e) => e + ' később',
    altKorabban: (e) => e + ' korábban',
    altNap: (n) => n + ' nappal',
    altHet: (n) => n + ' héttel',

    osszValasztottIdopont: 'Válassz időpontot',
    osszIfa: 'Idegenforgalmi adó',
    osszFoglaloMost: 'Ebből foglaló most',
    osszSzallasdij: 'Szállásdíj',
    osszKaucio: 'Kaució',
    osszAllapot: 'Állapot',
    osszVendegek: 'Vendégek',

    feltFoglalo: 'Foglaló',
    feltFoglaloOsszeg: (osszeg) => osszeg + ' átutalással — ezzel válik élővé a foglalás',
    feltFoglaloSzazalek: (szazalek) => 'A szállásdíj ' + szazalek + '%-a átutalással — ezzel válik élővé a foglalás',
    feltHatralek: 'Hátralék',
    feltHatralekSzoveg: 'Érkezés előtt 14 nappal átutalva, vagy készpénzben érkezéskor',
    feltIfaSzoveg: (osszeg) => osszeg + ' / fő / éj, 18 év felett — érkezéskor készpénzben',
    feltKaucioSzoveg: (osszeg) => osszeg + ' érkezéskor készpénzben, távozáskor visszajár',
    feltLemondas: 'Lemondás',
    feltLemondasSzoveg: (nap) => 'Érkezés előtt ' + nap + ' napon túl a foglalót visszafizetjük',
    feltTeljesHazirend: 'Teljes házirend',

    attekIdopont: 'Időpont',
    attekFekvohelyek: 'Fekvőhelyek',
    attekHaloszobakban: (n) => n + ' fő a hálószobákban',
    attekKanape: 'nappali kanapé beágyazva',
    attekCsakHalo: 'csak a hálószobák',
    attekGyerekagy: 'gyermekágy',
    attekEtetoszek: 'etetőszék',
    attekNemAdtadMeg: 'nem adtad meg',
    mitTortenik: 'Mi történik ezután?',
    mitTortenikSzoveg: (foglalo) => 'Átnézzük a naptárt, és 24 órán belül válaszolunk e-mailben. A visszaigazolás után a ' + foglalo + ' foglaló átutalásával válik élővé a foglalás.',
    elfogadom: (link) => ['Elfogadom a ', link],
    elfogadomLink: 'házirendet',
    kuldes: 'Kérés elküldése',

    hibaDatum: 'Válassz érkezési és távozási napot.',
    hibaNev: 'Írd ide a neved, hogy tudjunk megszólítani.',
    hibaEmail: 'Adj meg egy érvényes e-mail címet.',
    hibaFeltetel: 'A házirend elfogadása nélkül nem tudjuk rögzíteni a kérést.',

    kesz: 'Megkaptuk a kérésedet',
    keszSzoveg: (idoszak, vendegek, email) => idoszak + ', ' + vendegek + '. Küldtünk egy visszajelzést a ' + email + ' címre.',
    keszMasodik: (foglalo) => '24 órán belül írunk, hogy szabad-e a ház. A visszaigazolás után a ' + foglalo + ' foglaló átutalásával válik élővé a foglalás.',
    keszRogzitve: 'Kérés rögzítve',
    keszAzonosito: (a) => 'Azonosító: ' + a,
    keszLekerdezes: (link) => ['Ezzel az azonosítóval és az e-mail címeddel bármikor megnézheted a foglalásod a ', link, ' oldalon — lemondani is ott tudsz.'],
    keszFooldal: 'Vissza a főoldalra',
    keszFoglalasom: 'A foglalásom',

    /* --- Foglalásom --- */
    lekFolott: 'Foglalásom',
    lekCim: 'Nézd meg, hol tart a foglalásod.',
    lekBevezeto: (a, e) => ['Az azonosítót a kérés elküldése után kaptad e-mailben. Az e-mail címmel együtt azonosít, ezért mindkettő kell. (A demóban próbáld ki: ', a, ' és ', e, '.)'],
    lekAzonosito: 'Foglalási azonosító',
    lekEmail: 'E-mail cím',
    lekGomb: 'Foglalás megkeresése',
    lekNincs: 'Nem találtuk',
    lekNincsSzoveg: (tel) => 'Ezzel az azonosítóval és e-mail címmel nincs foglalásunk. Nézd meg a visszaigazoló levelet, vagy hívj minket: ' + tel + '.',

    allapotFuggoben: 'Függőben',
    allapotVisszaigazolt: 'Visszaigazolva',
    allapotLemondott: 'Lemondva',

    lemIngyenes: 'Ingyenes lemondás',
    lemIngyenesSzoveg: (datum) => datum + ' éjfélig díjmentesen lemondható, a foglalót visszautaljuk.',
    lemNemIngyenes: 'A foglaló már nem visszatéríthető',
    lemNemIngyenesSzoveg: (datum) => 'Az ingyenes lemondás határideje (' + datum + ') elmúlt. Lemondani továbbra is lehet, de a foglalót nem áll módunkban visszatéríteni.',
    lemMar: 'Ezt a foglalást lemondtuk',
    lemMarSzoveg: 'Ha mégis jönnétek, indíts egy új foglalást — szívesen látunk.',
    lemModositas: 'Módosítanék — hívlak',
    lemGomb: 'Foglalás lemondása',
    lemBiztos: 'Biztosan lemondod?',
    lemBiztosSzoveg: (idoszak) => idoszak + ' — ezt a foglalást lemondjuk, és a ház újra foglalhatóvá válik.',
    lemVisszajar: (osszeg) => 'Foglaló visszajár: ' + osszeg,
    lemNemJar: 'A foglaló nem téríthető vissza',
    lemIgen: 'Igen, lemondom',
    kaucioVisszatero: 'Visszatérő vendégként nem kérjük',
    kaucioErkezeskor: (osszeg) => osszeg + ' érkezéskor, távozáskor visszajár',
    ifaErkezeskor: (osszeg) => osszeg + ' — érkezéskor készpénzben',

    /* --- Házirend --- */
    hazirendFolott: 'Házirend',
    hazirendCim: 'Amiben megállapodunk.',
    hazirendBevezeto: 'Nem hosszú, és nincs benne csapda. A foglaló és a lemondás feltételei a foglalásnál is ott vannak.',

    /* --- Kapcsolat --- */
    kapcsolatFolott: 'Kapcsolat',
    kapcsolatCim: 'Kérdezz nyugodtan.',
    kapcsolatElerhetoseg: 'Elérhetőség',
    kapcsolatUtvonal: 'Útvonal a térképen',
    kapcsolatOdajutas: 'Odajutás',

    /* --- Lábléc --- */
    lablecBevezeto: (alap, pot) => 'Nyaraló a Kákafoki holtág partján, Békésszentandráson. Két hálószoba, nagy kert, medence és saját stég — ' + alap + ' + ' + pot + ' főnek, egyben kiadva.',
    lablecHaz: 'A ház',
    lablecHazFelszereltseg: 'A ház és felszereltség',
    lablecArak: 'Árak és feltételek',
    lablecKapcsolat: 'Kapcsolat',
    lablecJoTudni: 'Jó tudni',
    lablecLemondas: 'Lemondási feltételek',
    lablecGyik: 'Gyakori kérdések',
    lablecDemo: 'Demóadatok visszaállítása',

    /* --- Hibaüzenetek. A logika.js csak kódot ad vissza, a mondat itt
           készül el — így a szabályokhoz nem kell hozzányúlni, ha egy
           szöveg változik. --- */
    napNevek: ['vasárnap', 'hétfő', 'kedd', 'szerda', 'csütörtök', 'péntek', 'szombat'],
    hibaMult: 'Ez a dátum már elmúlt.',
    hibaLetszam: (max) => 'Legfeljebb ' + max + ' főt tudunk fogadni.',
    hibaRosszIdoszak: 'A távozás dátuma legyen későbbi az érkezésnél.',
    hibaMinEj: (n) => 'Ebben az időszakban legalább ' + n + ' éjszakát tudunk vállalni.',
    hibaTurnus: (n, nap) => 'Ebben az időszakban ' + n + ' éjszakás turnusokban lehet foglalni, ' + nap + 'i váltással.',
    hibaFoglalt: 'Ez az időpont sajnos már foglalt.',
    hibaAltalanos: 'Most nem sikerült. Próbáld újra.',
    /* --- Foglalás (C) --- */
    foglalasMegNemKell: 'Ez még csak kérés — amíg nem írunk vissza, nem kell fizetned semmit.',
    hibaCim: 'Nem ment el',
    kanapeFigyelmeztetes: (n) => n + ' fővel a nappali kanapéját ágyként készítjük elő.',
    mezoFizetes: 'A hátralék fizetése',
    sugoFizetes: 'A foglalót minden esetben átutalással kérjük.',
    fizetesAtutalas: 'Átutalással, érkezés előtt 14 nappal',
    fizetesKeszpenz: 'Készpénzzel, az érkezés napján',
    fizetesKeszpenzLeiras: 'Az idegenforgalmi adó és a kaució így is készpénzben.',
    hirlevel: 'Szóljatok, ha akciós hétvége lesz',
    nincsExtra: 'nincs',
    attekMegjegyzesed: 'Megjegyzésed:',
    elfogadomKetto: (a, b) => ['Elfogadom a ', a, ' és az ', b],
    elfogadomAdatLink: 'adatkezelési tájékoztatót',
    kuldesFolyamatban: 'Küldjük…',
    keszKaucio: (osszeg) => 'Érkezéskor ' + osszeg + ' kaució és az idegenforgalmi adó készpénzben.',
    allapotLezart: 'Lezárva',
    lekAzonositoMinta: 'RV-2026-0714',
    lekSugo: (minta) => ['Az azonosítót a kérés elküldése után kaptad e-mailben — ilyen formájú: ', minta, '. Az e-mail címmel együtt azonosít, ezért mindkettő kell.'],
    lekKeresFolyamatban: 'Keressük…',
    lemondasFolyamatban: 'Lemondjuk…',
    lemondasKesz: 'Kész',
    lemondasKeszVisszajar: 'Lemondtuk a foglalást, a foglalót visszautaljuk.',
    lemondasKeszSima: 'Lemondtuk a foglalást.',
    lemUjFoglalas: (link) => ['Ha mégis jönnétek, indíts egy ', link, ' — szívesen látunk.'],
    lemUjFoglalasLink: 'új foglalást',
    fizetesAllapot: { unpaid: 'Foglaló még nem érkezett meg', deposit_paid: 'A foglalót megkaptuk', paid: 'A teljes összeg rendezve', refunded: 'A foglalót visszautaltuk' },
    reszletekHazirend: (link) => ['A részletes feltételek a ', link, ' olvashatók.'],
    reszletekHazirendLink: 'házirendben',

    hibaNemMondhatoLe: 'Ezt a foglalást már nem lehet a felületen lemondani — hívj minket.',

  

    /* --- A többoldalas változathoz: környék, kapcsolat, adatkezelés, impresszum --- */
    reszletek: 'Részletek',
    haloPlusz: (n) => '+' + n + ' fő',
    kornyekGomb: 'Mit lehet itt csinálni',
    zaroNaptar: 'A naptárt mi vezetjük, és 24 órán belül válaszolunk.',
    gyikIrj: (link) => ['Ha valami nincs benne, ', link, '.'],
    gyikIrjLink: 'írj nyugodtan',
    vendegekSzama: 'Vendégek száma',
    savSzabad: (ej, osszeg) => 'Szabad — ' + ej + ' éj, összesen ' + osszeg,
    kornyekHeroFelirat: 'A Kákafoki holtág a kert végében — innen indulnak a kajakok.',
    kornyekOldalCim: 'A holtág, a gát és a környék.',
    kornyekOldalLead: 'Semmi sincs messze, és semmit nem kell előre megszervezni. Helyben lakunk, ezért bármikor kérdezhettek.',
    holFolott: 'Ide találsz',
    holCim: 'Hol van a ház.',
    holP1: 'Békésszentandráson, a Kákafoki holtág partján, természetvédelmi parkban. Budapesttől 150 km, autóval nagyjából két óra. Vonattal Szarvasig lehet jönni, onnan elmegyünk értetek.',
    holP2: 'A holtágon nem jár motorcsónak, így a víz csendes. A gátoldalon sík út vezet Szarvas és Gyomaendrőd felé — három kerékpár a háznál van.',
    utvonaltervezes: 'Útvonaltervezés',
    kerdesemVan: 'Kérdésem van',
    mikorJonnetek: 'Mikor jönnétek?',
    naptarBevezeto: 'A naptárt mi vezetjük — nézd meg, mikor szabad a ház.',
    kapcsolatLead: 'Helyben lakunk, a kulcsot mi adjuk át. Ha valami nem világos a foglalás előtt, elég egy telefon.',
    mezoUzenet: 'Miben segíthetünk?',
    mintaEmail: 'anna@example.hu',
    mintaUzenet: 'Öten jönnénk júliusban, két kisgyerekkel…',
    hibaUzenetSzoveg: 'Írj pár szót arról, miben segíthetünk.',
    hibaAdatkezeles: 'Az adatkezelési tájékoztató elfogadása nélkül nem tudjuk elküldeni.',
    adatkezelesElfogadom: 'Elolvastam az adatkezelési tájékoztatót',
    uzenetKeszCim: 'Megkaptuk az üzeneted',
    uzenetKeszSzoveg: '24 órán belül válaszolunk.',
    uzenetHiba: 'Most nem sikerült elküldeni. Próbáld újra, vagy hívj minket.',
    uzenetElkuldve: 'Elküldtük',
    uzenetElkuldveSzoveg: 'Ránézünk a naptárra, és 24 órán belül írunk a megadott címre.',
    uzenetKuldes: 'Üzenet elküldése',
    terkepCim: 'A ház a térképen',
    nemetorszagbol: '(Németországból)',
    zartUdvar: 'Zárt udvar',
    szabadIdopontok: 'Szabad időpontok megnézése',
    impresszumNtak: (szam) => 'Magánszálláshely · NTAK regisztrációs szám: ' + szam,
    adatBlokkok: (email) => [
      ['Milyen adatot kezelünk', [
        'Foglaláskor: név, e-mail cím, telefonszám, az érkezés és távozás dátuma, a vendégek száma és a megjegyzésed.',
        'Érkezéskor a jogszabály szerint a személyes dokumentumok adatai, a Nemzeti Turisztikai Adatszolgáltató Központ felé teljesítendő adatszolgáltatás miatt.',
      ]],
      ['Miért kezeljük', [
        'A foglalás visszaigazolásához és teljesítéséhez, valamint a számlázáshoz.',
        'A jogszabályi adatszolgáltatási kötelezettség teljesítéséhez (NTAK).',
      ]],
      ['Meddig őrizzük', [
        'A foglalással kapcsolatos adatokat a számviteli előírások szerinti ideig.',
        'A meg nem valósult érdeklődéseket legfeljebb egy évig.',
      ]],
      ['Kinek adjuk át', [
        'A jogszabály által előírt hatósági adatszolgáltatáson kívül senkinek.',
        'Ez a weboldal nem használ nyomkövető vagy hirdetési sütiket.',
      ]],
      ['A te jogaid', [
        'Kérheted a rólad tárolt adatok másolatát, helyesbítését vagy törlését.',
        'Írj a ' + email + ' címre, és 30 napon belül válaszolunk.',
      ]],
    ],
    adatMegjegyzes: 'Ez a tájékoztató a demó része; az éles indulás előtt érdemes jogásszal átnézetni.',
    nincsOldalCim: 'Ez az oldal nincs meg.',
    nincsOldalSzoveg: 'Lehet, hogy elírtuk a linket. A ház, a szobák és a foglalás innen mind elérhető.',
    hazOsszesKep: (n) => 'Mind a ' + n + ' kép',
    hazHaloBevezeto: (alap, max) => 'A két emeleti hálószoba adja az alap ' + alap + ' fekvőhelyet. A nappali kanapéját kérésre ágyazzuk be további két főnek — a házirend szerint legfeljebb ' + max + '-en lehettek a házban.',
    joTudniCim: 'Amit a foglalás előtt érdemes átfutni.',
    galeriaHazAlt: 'A Riverside nyaraló',
    fotoMegnyitasa: (nev) => nev + ' — fotó megnyitása',
    galeriaTovabbiFoto: (n) => '+' + n + ' fotó',
    fotoNagyitasa: (nev) => nev + ' — nagyítás',
    kotottTurnus: 'Kötött turnus',
    arakTurnusMegjegyzes: 'Minden időszakban minimum három éjszakára lehet foglalni, bármelyik naptól. Nyárra sincs külön szabály.',
    feltetelekFolott: 'Feltételek',
    feltetelekCim: 'Foglaló, kaució, lemondás.',
    fizetesHogyanCim: 'Hogyan megy a fizetés',
    fizetesLepesek: [
      'Elküldöd a foglalási kérést, mi 24 órán belül válaszolunk.',
      'A visszaigazolás után átutalod a foglalót — ezzel válik élővé a foglalás.',
      'A hátralék érkezés előtt 14 nappal átutalva, vagy készpénzben érkezéskor.',
      'Érkezéskor készpénzben az idegenforgalmi adó és a kaució.',
    ],
    teljesLista: 'A teljes lista',
    kerdesVan: 'Kérdés van?',
    kerdesVanSzoveg: 'A nap 24 órájában hívhatod a kapcsolattartót. Bármilyen panaszt figyelembe veszünk, és lehetőség szerint helyben megoldunk.',
    hazirendElfogadva: 'A nyaraló foglalásával a házirendet elfogadottnak tekintjük.',
  },

  /* ==========================================================
     NÉMET — DEUTSCH
     ========================================================== */
  de: {
    nyelvNeve: 'Deutsch',
    kod: 'de',

    /* --- Schlafplätze: eine einzige Formulierung, überall dieselbe --- */
    ferohely: (alap, pot) => alap + ' + ' + pot + ' Personen',
    ferohelySugo: (alap, pot, max) => alap + ' Personen in den Betten, weitere ' + pot + ' auf dem Sofa im Wohnzimmer — höchstens ' + max + ' Personen.',
    mezoVendegek: 'Gäste',
    nincsGyerek: 'keine Kinder',
    ugrasTartalomra: 'Zum Inhalt springen',
    vendeghaz: 'Ferienhaus',
    adatkezelesLeiras: 'Welche Daten wir bei der Buchung erheben, warum wir sie verarbeiten, wie lange wir sie aufbewahren und an wen wir sie weitergeben.',
    impresszumLeiras: 'Betreiber, Anschrift, Kontakt und NTAK-Registriernummer des Ferienhauses Riverside in Békésszentandrás.',
    arKartyaMibe: (alap, pot) => 'für das ganze Haus, für ' + alap + ' + ' + pot + ' Personen',
    arKartyaTol: 'ab',

    menuHaz: 'Das Haus',
    menuArak: 'Preise',
    menuGaleria: 'Galerie',
    menuKapcsolat: 'Kontakt',
    menuFoglalas: 'Buchen',
    menuFoglalasom: 'Meine Buchung',
    menuHazirend: 'Hausordnung',
    menuAdatkezeles: 'Datenschutz',
    menuImpresszum: 'Impressum',
    adatkezelesCim: 'Wie wir mit euren Daten umgehen.',
    impresszumCim: 'Wer die Unterkunft betreibt.',
    impresszumSzallashely: 'Unterkunft',
    impresszumTarhely: 'Hosting und Betrieb',
    impresszumTarhelySzoveg: 'Die Angaben zum Hosting-Anbieter folgen vor dem Live-Start.',
    menuGomb: 'Menü',
    nyelvvalaszto: 'Sprache',

    tovabb: 'Weiter',
    vissza: 'Zurück',
    megsem: 'Abbrechen',
    bezaras: 'Schließen',
    elozo: 'Zurück',
    kovetkezo: 'Weiter',
    nemKotelezo: 'optional',
    ej: 'Nächte',
    ejszaka: 'Nächte',
    fok: (n) => n + (n === 1 ? ' Person' : ' Personen'),
    felnottek: (n) => n + (n === 1 ? ' Erwachsener' : ' Erwachsene'),
    gyerekek: (n) => n + (n === 1 ? ' Kind' : ' Kinder'),
    perEj: '/ Nacht',
    aTeljesHazra: 'für das ganze Haus',
    osszesen: 'Gesamt',
    nincsFelar: 'ohne Aufpreis',

    heroFolott: 'Ferienhaus am Altarm der Körös',
    heroCim: 'Ein paar Tage am Wasser.',
    heroLead: (alap, pot) => 'Zwei Schlafzimmer, großer Garten, Pool, Sauna und eigener Steg — das ganze Haus gehört euch, für ' + alap + ' + ' + pot + ' Personen. Ein ruhiger Ort — kein Partyhaus.',
    heroGomb1: 'Buchen',
    heroGomb2: 'Das Haus ansehen',

    introFolott: 'Was das hier ist',
    introCim: 'Altarm, geschlossener Garten, 85 Quadratmeter.',

    haloFolott: 'Schlafplätze',
    haloCim: (alap, pot) => alap + ' + ' + pot + ' Schlafplätze – auch für die Kinder ist Platz.',
    haloBevezeto: 'Zwei Schlafzimmer im Obergeschoss, das Sofa im Wohnzimmer beziehen wir auf Wunsch. Laut Hausordnung dürfen höchstens sieben Personen im Haus sein.',

    velemenyFolott: 'Gäste',
    velemenyCim: 'Was Stammgäste sagen.',
    velemenyDemo: 'Demodaten: Diese Texte wurden für die Präsentation erstellt und stammen nicht von echten Gästen.',

    kornyekFolott: 'Umgebung',
    kornyekCim: 'Was es rund ums Haus gibt.',

    gyikFolott: 'Häufige Fragen',
    gyikCim: 'Was vor der Buchung meistens gefragt wird.',
    gyikTeljes: (link) => ['Die vollständigen Regeln stehen in der ', link, '.'],
    gyikHazirendLink: 'Hausordnung',

    zaroCim: 'Schaut, wann noch frei ist.',
    zaroBevezeto: (ar) => 'Ab ' + ar + ' / Nacht für das ganze Haus. Den Kalender führen wir selbst und antworten innerhalb von 24 Stunden.',
    zaroGomb: 'Buchung starten',

    hazFolott: 'Das Haus',
    hazCim: 'Das ganze Haus gehört nur euch.',
    hazMeta: (m2, halo, furdo, alap, pot) =>
      m2 + ' m² · ' + halo + ' · ' + furdo + ' Bäder · ' + alap + '+' + pot + ' Personen',
    hazKetHalo: 'zwei Schlafzimmer und Wohnzimmer',
    hazMindKep: (n) => 'Alle ' + n + ' Bilder →',
    felszereltsegFolott: 'Ausstattung',
    felszereltsegCim: 'Was im Haus und im Garten da ist.',
    arbanFolott: 'Im Preis enthalten',
    arbanCim: 'Und was nicht.',
    arbanBenne: 'Enthalten',
    arbanNincs: 'Nicht enthalten',
    kerésre: (n) => '+' + n + ' auf Wunsch',

    arakFolott: 'Preise',
    arakCim: 'Der Preis gilt für das ganze Haus.',
    arakBevezeto: (max) => 'Die Personenzahl ändert den Übernachtungspreis nicht — nur die Kurtaxe. Höchstens ' + max + ' Personen.',
    tablaSzezon: 'Saison',
    tablaIdoszak: 'Zeitraum',
    tablaAr: 'Preis / Nacht',
    tablaSzabaly: 'Regel',
    szabalyTurnus: (n) => 'genau ' + n + ' Nächte, Samstag–Samstag',
    szabalyMin: (n) => 'mind. ' + n + ' Nächte',
    fizetesiFeltetelek: 'Zahlungsbedingungen',

    galeriaFolott: 'Galerie',
    galeriaCim: (n) => 'Lernt das Haus in Bildern kennen.',
    galeriaBevezeto: 'Was auf den Fotos zu sehen ist, gibt es auch. Am Ende der Serie stehen die 3D-Grundrisse von Erd- und Obergeschoss.',
    galeriaMind: 'Alle',
    galeriaSzuresCimke: 'Fotos filtern',
    cimkeFotok: (mi, n) => mi + ' — ' + n + ' Fotos in der Galerie',
    arakTelMegjegyzes: 'Die Wintersaison läuft vom 1. Dezember bis Ende Februar und schließt Weihnachten und Neujahr ein — zum selben Preis wie die Hauptsaison im Sommer.',
    galeriaCimkeSzuro: (mi) => 'Nur diese: ' + mi,
    fotoNagyitas: 'Vergrößern',

    foglalasFolott: 'Buchung',
    foglalasCim: 'Schauen wir, wann ihr kommt.',
    lepes1: 'Termin und Gäste',
    lepes2: 'Daten',
    lepes3: 'Übersicht',

    mezoIdopont: 'Zeitraum',
    mezoErkezes: 'Anreise',
    mezoTavozas: 'Abreise',
    mezoFelnott: 'Erwachsene',
    mezoGyerek: 'Kinder',
    mezoFekvohelyek: 'Schlafplätze',
    mezoExtrak: 'Extras',
    mezoNev: 'Name',
    mezoEmail: 'E-Mail',
    mezoTelefon: 'Telefonnummer',
    mezoMegjegyzes: 'Anmerkung',

    sugoTurnus: (n) => 'genau ' + n + ' Nächte buchbar, Samstag bis Samstag',
    sugoMinEj: (n) => 'ab ' + n + ' Nächten buchbar',
    sugoFelnott: 'Ab 18 Jahren — für sie fällt die Kurtaxe an.',
    sugoGyerek: 'Unter 18 Jahren, kurtaxefrei.',
    sugoExtrak: 'Jederzeit änderbar, solange wir noch nicht geantwortet haben.',
    sugoTelefon: 'Nur falls wir zurückrufen müssen.',
    sugoMegjegyzes: 'Allergie, frühe Anreise, alles Weitere.',
    mintaNev: 'Anna Müller',
    mintaMegjegyzes: 'Wir kommen mit zwei kleinen Kindern und würden den Hund mitbringen.',

    fekvohelyBevezeto: (alap, pot) => ['Für ' + alap + ' Personen gibt es reguläre Schlafplätze', ' in den zwei Schlafzimmern im Obergeschoss, für weitere ' + pot + ' Personen lässt sich das Sofa im Wohnzimmer als Bett nutzen.'],
    kanapeCimke: 'Sofa im Wohnzimmer bitte als Bett herrichten',
    kanapeKell: (n) => 'Bei ' + n + ' Personen ist das nötig, deshalb haben wir es angehakt.',
    kanapeNemKell: 'Wenn ihr es nicht braucht, bleibt es Sitzgarnitur.',
    gyerekagyCimke: 'Kinderbett im Dreibettzimmer',
    gyerekagyLeiras: 'Kostenlos und zählt nicht zur Belegung.',
    etetoszekCimke: 'Hochstuhl',
    etetoszekLeiras: 'Kostenlos, sagt vorher Bescheid und wir stellen ihn bereit.',

    naptarSugo: 'Erst auf die Anreise klicken, dann auf die Abreise',
    naptarSzabad: 'frei',
    naptarFoglalt: 'belegt',
    naptarKivalasztva: 'ausgewählt',
    naptarNapCimke: (nap, foglalt) => nap + (foglalt ? ' — belegt' : ''),
    elozoHonap: 'Voriger Monat',
    kovetkezoHonap: 'Nächster Monat',

    altCim: 'Frei ist das Haus dagegen hier',
    altHaNemJo: 'Wenn keiner davon passt, schreibt oder ruft an — manchmal wird eine Buchung doch noch frei.',
    altNincs: 'In den nächsten Monaten haben wir keinen freien Zeitraum in dieser Länge gefunden. Schreibt uns, und wir schauen, was möglich ist.',
    altUgyanaznap: 'am selben Tag',
    altKesobb: (e) => e + ' später',
    altKorabban: (e) => e + ' früher',
    altNap: (n) => n + (n === 1 ? ' Tag' : ' Tage'),
    altHet: (n) => n + (n === 1 ? ' Woche' : ' Wochen'),

    osszValasztottIdopont: 'Zeitraum wählen',
    osszIfa: 'Kurtaxe',
    osszFoglaloMost: 'Davon Anzahlung jetzt',
    osszSzallasdij: 'Übernachtung',
    osszKaucio: 'Kaution',
    osszAllapot: 'Status',
    osszVendegek: 'Gäste',

    feltFoglalo: 'Anzahlung',
    feltFoglaloOsszeg: (osszeg) => osszeg + ' per Überweisung — damit wird die Buchung verbindlich',
    feltFoglaloSzazalek: (szazalek) => szazalek + ' % des Übernachtungspreises per Überweisung — damit wird die Buchung verbindlich',
    feltHatralek: 'Restbetrag',
    feltHatralekSzoveg: '14 Tage vor Anreise überwiesen oder bei Anreise in bar',
    feltIfaSzoveg: (osszeg) => osszeg + ' / Person / Nacht ab 18 Jahren — bei Anreise in bar',
    feltKaucioSzoveg: (osszeg) => osszeg + ' bei Anreise in bar, bei Abreise zurück',
    feltLemondas: 'Stornierung',
    feltLemondasSzoveg: (nap) => 'Bis ' + nap + ' Tage vor Anreise erstatten wir die Anzahlung',
    feltTeljesHazirend: 'Vollständige Hausordnung',

    attekIdopont: 'Zeitraum',
    attekFekvohelyek: 'Schlafplätze',
    attekHaloszobakban: (n) => n + ' Personen in den Schlafzimmern',
    attekKanape: 'Sofa als Bett hergerichtet',
    attekCsakHalo: 'nur die Schlafzimmer',
    attekGyerekagy: 'Kinderbett',
    attekEtetoszek: 'Hochstuhl',
    attekNemAdtadMeg: 'nicht angegeben',
    mitTortenik: 'Wie geht es weiter?',
    mitTortenikSzoveg: (foglalo) => 'Wir sehen im Kalender nach und antworten innerhalb von 24 Stunden per E-Mail. Nach unserer Bestätigung wird die Buchung mit der Überweisung der Anzahlung von ' + foglalo + ' verbindlich.',
    elfogadom: (link) => ['Ich akzeptiere die ', link],
    elfogadomLink: 'Hausordnung',
    kuldes: 'Anfrage senden',

    hibaDatum: 'Bitte Anreise- und Abreisetag wählen.',
    hibaNev: 'Bitte trage deinen Namen ein, damit wir dich ansprechen können.',
    hibaEmail: 'Bitte gib eine gültige E-Mail-Adresse an.',
    hibaFeltetel: 'Ohne Zustimmung zur Hausordnung können wir die Anfrage nicht aufnehmen.',

    kesz: 'Wir haben deine Anfrage erhalten',
    keszSzoveg: (idoszak, vendegek, email) => idoszak + ', ' + vendegek + '. Eine Bestätigung ist an ' + email + ' unterwegs.',
    keszMasodik: (foglalo) => 'Wir melden uns innerhalb von 24 Stunden, ob das Haus frei ist. Nach der Bestätigung wird die Buchung mit der Überweisung der Anzahlung von ' + foglalo + ' verbindlich.',
    keszRogzitve: 'Anfrage aufgenommen',
    keszAzonosito: (a) => 'Buchungsnummer: ' + a,
    keszLekerdezes: (link) => ['Mit dieser Buchungsnummer und deiner E-Mail-Adresse kannst du deine Buchung jederzeit auf der Seite ', link, ' ansehen — stornieren geht dort ebenfalls.'],
    keszFooldal: 'Zurück zur Startseite',
    keszFoglalasom: 'Meine Buchung',

    lekFolott: 'Meine Buchung',
    lekCim: 'Sieh nach, wie weit deine Buchung ist.',
    lekBevezeto: (a, e) => ['Die Buchungsnummer hast du nach dem Absenden per E-Mail bekommen. Sie gilt nur zusammen mit der E-Mail-Adresse, deshalb sind beide nötig. (In der Demo zum Ausprobieren: ', a, ' und ', e, '.)'],
    lekAzonosito: 'Buchungsnummer',
    lekEmail: 'E-Mail-Adresse',
    lekGomb: 'Buchung suchen',
    lekNincs: 'Nicht gefunden',
    lekNincsSzoveg: (tel) => 'Zu dieser Buchungsnummer und E-Mail-Adresse haben wir keine Buchung. Sieh in der Bestätigungsmail nach oder ruf uns an: ' + tel + '.',

    allapotFuggoben: 'Offen',
    allapotVisszaigazolt: 'Bestätigt',
    allapotLemondott: 'Storniert',

    lemIngyenes: 'Kostenlose Stornierung',
    lemIngyenesSzoveg: (datum) => 'Bis zum ' + datum + ' um Mitternacht kostenlos stornierbar, die Anzahlung erstatten wir.',
    lemNemIngyenes: 'Die Anzahlung ist nicht mehr erstattbar',
    lemNemIngyenesSzoveg: (datum) => 'Die Frist für die kostenlose Stornierung (' + datum + ') ist vorbei. Stornieren ist weiterhin möglich, die Anzahlung können wir jedoch nicht erstatten.',
    lemMar: 'Diese Buchung haben wir storniert',
    lemMarSzoveg: 'Wenn ihr doch kommen möchtet, startet einfach eine neue Buchung — ihr seid willkommen.',
    lemModositas: 'Ich möchte ändern — ich rufe an',
    lemGomb: 'Buchung stornieren',
    lemBiztos: 'Wirklich stornieren?',
    lemBiztosSzoveg: (idoszak) => idoszak + ' — wir stornieren diese Buchung, und das Haus wird wieder buchbar.',
    lemVisszajar: (osszeg) => 'Anzahlung wird erstattet: ' + osszeg,
    lemNemJar: 'Die Anzahlung wird nicht erstattet',
    lemIgen: 'Ja, stornieren',
    kaucioVisszatero: 'Als Stammgast entfällt sie',
    kaucioErkezeskor: (osszeg) => osszeg + ' bei Anreise, bei Abreise zurück',
    ifaErkezeskor: (osszeg) => osszeg + ' — bei Anreise in bar',

    hazirendFolott: 'Hausordnung',
    hazirendCim: 'Worauf wir uns einigen.',
    hazirendBevezeto: 'Nicht lang und ohne versteckte Klauseln. Anzahlung und Stornobedingungen stehen auch bei der Buchung.',

    kapcsolatFolott: 'Kontakt',
    kapcsolatCim: 'Fragt einfach.',
    kapcsolatElerhetoseg: 'Erreichbarkeit',
    kapcsolatUtvonal: 'Route auf der Karte',
    kapcsolatOdajutas: 'Anfahrt',

    lablecBevezeto: (alap, pot) => 'Ferienhaus am Altarm Kákafok in Békésszentandrás. Zwei Schlafzimmer, großer Garten, Pool und eigener Steg — für ' + alap + ' + ' + pot + ' Personen, als Ganzes vermietet.',
    lablecHaz: 'Das Haus',
    lablecHazFelszereltseg: 'Haus und Ausstattung',
    lablecArak: 'Preise und Bedingungen',
    lablecKapcsolat: 'Kontakt',
    lablecJoTudni: 'Gut zu wissen',
    lablecLemondas: 'Stornobedingungen',
    lablecGyik: 'Häufige Fragen',
    lablecDemo: 'Demodaten zurücksetzen',

    /* --- Fehlermeldungen --- */
    napNevek: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    hibaMult: 'Dieses Datum liegt in der Vergangenheit.',
    hibaLetszam: (max) => 'Wir können höchstens ' + max + ' Personen aufnehmen.',
    hibaRosszIdoszak: 'Die Abreise muss nach der Anreise liegen.',
    hibaMinEj: (n) => 'In diesem Zeitraum können wir mindestens ' + n + ' Nächte anbieten.',
    hibaTurnus: (n, nap) => 'In diesem Zeitraum ist nur eine feste Woche mit ' + n + ' Nächten buchbar, mit Wechsel am ' + nap + '.',
    hibaFoglalt: 'Dieser Zeitraum ist leider schon vergeben.',
    hibaAltalanos: 'Das hat gerade nicht geklappt. Bitte versuch es noch einmal.',
    /* --- Buchung (C) --- */
    foglalasMegNemKell: 'Das ist erst eine Anfrage — bis wir antworten, ist nichts zu zahlen.',
    hibaCim: 'Nicht abgeschickt',
    kanapeFigyelmeztetes: (n) => 'Bei ' + n + ' Personen richten wir das Sofa im Wohnzimmer als Bett her.',
    mezoFizetes: 'Zahlung des Restbetrags',
    sugoFizetes: 'Die Anzahlung bitten wir in jedem Fall per Überweisung.',
    fizetesAtutalas: 'Per Überweisung, 14 Tage vor Anreise',
    fizetesKeszpenz: 'Bar am Anreisetag',
    fizetesKeszpenzLeiras: 'Kurtaxe und Kaution sind auch dann in bar fällig.',
    hirlevel: 'Sagt Bescheid, wenn es ein Angebotswochenende gibt',
    nincsExtra: 'keine',
    attekMegjegyzesed: 'Deine Anmerkung:',
    elfogadomKetto: (a, b) => ['Ich akzeptiere die ', a, ' und die ', b],
    elfogadomAdatLink: 'Datenschutzhinweise',
    kuldesFolyamatban: 'Wird gesendet…',
    keszKaucio: (osszeg) => 'Bei Anreise ' + osszeg + ' Kaution und die Kurtaxe in bar.',
    allapotLezart: 'Abgeschlossen',
    lekAzonositoMinta: 'RV-2026-0714',
    lekSugo: (minta) => ['Die Buchungsnummer hast du nach dem Absenden per E-Mail bekommen — sie sieht so aus: ', minta, '. Sie gilt nur zusammen mit der E-Mail-Adresse, deshalb sind beide nötig.'],
    lekKeresFolyamatban: 'Wird gesucht…',
    lemondasFolyamatban: 'Wird storniert…',
    lemondasKesz: 'Erledigt',
    lemondasKeszVisszajar: 'Wir haben die Buchung storniert und erstatten die Anzahlung.',
    lemondasKeszSima: 'Wir haben die Buchung storniert.',
    lemUjFoglalas: (link) => ['Wenn ihr doch kommen möchtet, startet einfach eine ', link, ' — ihr seid willkommen.'],
    lemUjFoglalasLink: 'neue Buchung',
    fizetesAllapot: { unpaid: 'Anzahlung noch nicht eingegangen', deposit_paid: 'Anzahlung erhalten', paid: 'Vollständig bezahlt', refunded: 'Anzahlung erstattet' },
    reszletekHazirend: (link) => ['Die genauen Bedingungen stehen in der ', link, '.'],
    reszletekHazirendLink: 'Hausordnung',

    hibaNemMondhatoLe: 'Diese Buchung lässt sich hier nicht mehr stornieren — ruf uns bitte an.',

  

    /* --- A többoldalas változathoz: környék, kapcsolat, adatkezelés, impresszum --- */
    reszletek: 'Details',
    haloPlusz: (n) => '+' + n + (n === 1 ? ' Person' : ' Personen'),
    kornyekGomb: 'Was man hier unternehmen kann',
    zaroNaptar: 'Den Kalender führen wir selbst und antworten innerhalb von 24 Stunden.',
    gyikIrj: (link) => ['Wenn etwas fehlt, ', link, '.'],
    gyikIrjLink: 'schreibt uns einfach',
    vendegekSzama: 'Anzahl der Gäste',
    savSzabad: (ej, osszeg) => 'Frei — ' + ej + (ej === 1 ? ' Nacht' : ' Nächte') + ', insgesamt ' + osszeg,
    kornyekHeroFelirat: 'Der Kákafok-Altarm am Ende des Gartens — von hier starten die Kajaks.',
    kornyekOldalCim: 'Der Altarm, der Damm und die Umgebung.',
    kornyekOldalLead: 'Nichts ist weit, und nichts muss vorher organisiert werden. Wir wohnen vor Ort, fragt uns jederzeit.',
    holFolott: 'So findet ihr uns',
    holCim: 'Wo das Haus liegt.',
    holP1: 'In Békésszentandrás, am Ufer des Kákafok-Altarms, in einem Naturschutzpark. Von Budapest 150 km, mit dem Auto etwa zwei Stunden. Mit der Bahn könnt ihr bis Szarvas kommen, von dort holen wir euch ab.',
    holP2: 'Auf dem Altarm fahren keine Motorboote, das Wasser bleibt ruhig. Auf dem Damm führt ein flacher Weg Richtung Szarvas und Gyomaendrőd — drei Fahrräder stehen am Haus.',
    utvonaltervezes: 'Route planen',
    kerdesemVan: 'Ich habe eine Frage',
    mikorJonnetek: 'Wann möchtet ihr kommen?',
    naptarBevezeto: 'Den Kalender führen wir selbst — schaut nach, wann das Haus frei ist.',
    kapcsolatLead: 'Wir wohnen vor Ort und übergeben den Schlüssel persönlich. Wenn vor der Buchung etwas unklar ist, genügt ein Anruf.',
    mezoUzenet: 'Womit können wir helfen?',
    mintaEmail: 'anna@example.de',
    mintaUzenet: 'Wir kämen im Juli zu fünft, mit zwei kleinen Kindern…',
    hibaUzenetSzoveg: 'Schreib bitte ein paar Worte dazu, womit wir helfen können.',
    hibaAdatkezeles: 'Ohne Zustimmung zur Datenschutzerklärung können wir die Nachricht nicht senden.',
    adatkezelesElfogadom: 'Ich habe die Datenschutzerklärung gelesen',
    uzenetKeszCim: 'Wir haben deine Nachricht erhalten',
    uzenetKeszSzoveg: 'Wir antworten innerhalb von 24 Stunden.',
    uzenetHiba: 'Das Senden hat gerade nicht geklappt. Versuch es noch einmal oder ruf uns an.',
    uzenetElkuldve: 'Abgeschickt',
    uzenetElkuldveSzoveg: 'Wir sehen im Kalender nach und schreiben innerhalb von 24 Stunden an die angegebene Adresse.',
    uzenetKuldes: 'Nachricht senden',
    terkepCim: 'Das Haus auf der Karte',
    nemetorszagbol: '(aus Deutschland)',
    zartUdvar: 'Geschlossener Hof',
    szabadIdopontok: 'Freie Termine ansehen',
    impresszumNtak: (szam) => 'Private Unterkunft · NTAK-Registriernummer: ' + szam,
    adatBlokkok: (email) => [
      ['Welche Daten wir verarbeiten', [
        'Bei der Buchung: Name, E-Mail-Adresse, Telefonnummer, An- und Abreisedatum, Zahl der Gäste und deine Anmerkung.',
        'Bei der Anreise gesetzlich vorgeschrieben die Daten der Ausweisdokumente, wegen der Meldung an das ungarische Tourismus-Datenzentrum (NTAK).',
      ]],
      ['Wozu wir sie verarbeiten', [
        'Zur Bestätigung und Durchführung der Buchung sowie zur Rechnungsstellung.',
        'Zur Erfüllung der gesetzlichen Meldepflicht (NTAK).',
      ]],
      ['Wie lange wir sie aufbewahren', [
        'Buchungsbezogene Daten so lange, wie es die Buchhaltungsvorschriften verlangen.',
        'Anfragen, aus denen keine Buchung wurde, höchstens ein Jahr.',
      ]],
      ['An wen wir sie weitergeben', [
        'Außer der gesetzlich vorgeschriebenen Behördenmeldung an niemanden.',
        'Diese Website verwendet keine Tracking- oder Werbe-Cookies.',
      ]],
      ['Deine Rechte', [
        'Du kannst eine Kopie, die Berichtigung oder die Löschung deiner Daten verlangen.',
        'Schreib an ' + email + ', wir antworten innerhalb von 30 Tagen.',
      ]],
    ],
    adatMegjegyzes: 'Diese Erklärung gehört zur Demo; vor dem Live-Start sollte ein Jurist sie prüfen.',
    nincsOldalCim: 'Diese Seite gibt es nicht.',
    nincsOldalSzoveg: 'Vielleicht haben wir den Link vertippt. Das Haus, die Zimmer und die Buchung sind von hier aus alle erreichbar.',
    hazOsszesKep: (n) => 'Alle ' + n + ' Bilder',
    hazHaloBevezeto: (alap, max) => 'Die beiden Schlafzimmer im Obergeschoss bringen die ' + alap + ' festen Schlafplätze. Das Sofa im Wohnzimmer beziehen wir auf Wunsch für zwei weitere Personen — laut Hausordnung dürft ihr zu höchstens ' + max + ' im Haus sein.',
    joTudniCim: 'Was ihr vor der Buchung kurz überfliegen solltet.',
    galeriaHazAlt: 'Das Ferienhaus Riverside',
    fotoMegnyitasa: (nev) => nev + ' — Foto öffnen',
    galeriaTovabbiFoto: (n) => '+' + n + ' Fotos',
    fotoNagyitasa: (nev) => nev + ' — vergrößern',
    kotottTurnus: 'Feste Woche',
    arakTurnusMegjegyzes: 'In jedem Zeitraum sind mindestens drei Nächte buchbar, beginnend an jedem beliebigen Tag. Für den Sommer gilt keine Sonderregel.',
    feltetelekFolott: 'Bedingungen',
    feltetelekCim: 'Anzahlung, Kaution, Stornierung.',
    fizetesHogyanCim: 'So läuft die Zahlung',
    fizetesLepesek: [
      'Du schickst die Buchungsanfrage, wir antworten innerhalb von 24 Stunden.',
      'Nach der Bestätigung überweist du die Anzahlung — damit wird die Buchung verbindlich.',
      'Der Restbetrag 14 Tage vor Anreise per Überweisung oder bei Anreise in bar.',
      'Bei Anreise in bar: Kurtaxe und Kaution.',
    ],
    teljesLista: 'Die ganze Liste',
    kerdesVan: 'Noch Fragen?',
    kerdesVanSzoveg: 'Du kannst uns rund um die Uhr anrufen. Jede Beanstandung nehmen wir ernst und lösen sie nach Möglichkeit gleich vor Ort.',
    hazirendElfogadva: 'Mit der Buchung des Ferienhauses gilt die Hausordnung als angenommen.',
  },

  /* ==========================================================
     ANGOL — ENGLISH
     ========================================================== */
  en: {
    nyelvNeve: 'English',
    kod: 'en',

    /* --- Capacity: one wording, used everywhere --- */
    ferohely: (alap, pot) => alap + ' + ' + pot + ' guests',
    ferohelySugo: (alap, pot, max) => alap + ' guests in the beds, ' + pot + ' more on the living-room sofa — ' + max + ' at most.',
    mezoVendegek: 'Guests',
    nincsGyerek: 'no children',
    ugrasTartalomra: 'Skip to content',
    vendeghaz: 'guest house',
    adatkezelesLeiras: 'What data we ask for when you book, why we process it, how long we keep it and who we share it with. The Riverside privacy notice.',
    impresszumLeiras: 'Who runs the Riverside guest house, its address, contact details and NTAK registration number in Békésszentandrás.',
    arKartyaMibe: (alap, pot) => 'for the whole house, for ' + alap + ' + ' + pot + ' guests',
    arKartyaTol: 'from',

    menuHaz: 'The house',
    menuArak: 'Prices',
    menuGaleria: 'Gallery',
    menuKapcsolat: 'Contact',
    menuFoglalas: 'Book',
    menuFoglalasom: 'My booking',
    menuHazirend: 'House rules',
    menuAdatkezeles: 'Privacy',
    menuImpresszum: 'Imprint',
    adatkezelesCim: 'How we handle your data.',
    impresszumCim: 'Who runs the property.',
    impresszumSzallashely: 'Property',
    impresszumTarhely: 'Hosting and operation',
    impresszumTarhelySzoveg: 'The hosting provider details will be added before going live.',
    menuGomb: 'Menu',
    nyelvvalaszto: 'Language',

    tovabb: 'Next',
    vissza: 'Back',
    megsem: 'Cancel',
    bezaras: 'Close',
    elozo: 'Previous',
    kovetkezo: 'Next',
    nemKotelezo: 'optional',
    ej: 'nights',
    ejszaka: 'nights',
    fok: (n) => n + (n === 1 ? ' guest' : ' guests'),
    felnottek: (n) => n + (n === 1 ? ' adult' : ' adults'),
    gyerekek: (n) => n + (n === 1 ? ' child' : ' children'),
    perEj: '/ night',
    aTeljesHazra: 'for the whole house',
    osszesen: 'Total',
    nincsFelar: 'no extra charge',

    heroFolott: 'A holiday house on the Körös backwater',
    heroCim: 'A few days by the water.',
    heroLead: (alap, pot) => 'Two bedrooms, a large garden, a pool, a sauna and a private jetty — the whole house is yours, for ' + alap + ' + ' + pot + ' guests. A quiet place — not a party house.',
    heroGomb1: 'Book',
    heroGomb2: 'See the house',

    introFolott: 'What this place is',
    introCim: 'Backwater, walled garden, 85 square metres.',

    haloFolott: 'Sleeping arrangements',
    haloCim: (alap, pot) => alap + ' + ' + pot + ' beds – there is room for the children too.',
    haloBevezeto: 'Two bedrooms upstairs, and we make up the living-room sofa on request. House rules allow seven guests at most.',

    velemenyFolott: 'Guests',
    velemenyCim: 'What returning guests say.',
    velemenyDemo: 'Demo data: these texts were written for the presentation and do not come from real guests.',

    kornyekFolott: 'Around here',
    kornyekCim: 'What there is around the house.',

    gyikFolott: 'Frequent questions',
    gyikCim: 'What people ask before booking.',
    gyikTeljes: (link) => ['The full rules are in the ', link, '.'],
    gyikHazirendLink: 'house rules',

    zaroCim: 'See when the house is free.',
    zaroBevezeto: (ar) => 'From ' + ar + ' / night for the whole house. We keep the calendar ourselves and reply within 24 hours.',
    zaroGomb: 'Start booking',

    hazFolott: 'The house',
    hazCim: 'The whole house is just yours.',
    hazMeta: (m2, halo, furdo, alap, pot) =>
      m2 + ' m² · ' + halo + ' · ' + furdo + ' bathrooms · ' + alap + '+' + pot + ' guests',
    hazKetHalo: 'two bedrooms and a living room',
    hazMindKep: (n) => 'All ' + n + ' photos →',
    felszereltsegFolott: 'Facilities',
    felszereltsegCim: 'What you get in the house and the garden.',
    arbanFolott: 'What the price covers',
    arbanCim: 'And what it does not.',
    arbanBenne: 'Included',
    arbanNincs: 'Not included',
    kerésre: (n) => '+' + n + ' on request',

    arakFolott: 'Prices',
    arakCim: 'The price is for the whole house.',
    arakBevezeto: (max) => 'The number of guests does not change the accommodation price — only the tourist tax. Up to ' + max + ' guests.',
    tablaSzezon: 'Season',
    tablaIdoszak: 'Period',
    tablaAr: 'Price / night',
    tablaSzabaly: 'Rule',
    szabalyTurnus: (n) => 'exactly ' + n + ' nights, Saturday to Saturday',
    szabalyMin: (n) => 'min. ' + n + ' nights',
    fizetesiFeltetelek: 'Payment terms',

    galeriaFolott: 'Gallery',
    galeriaCim: (n) => 'Get to know the house in pictures.',
    galeriaBevezeto: 'What you see in the photos is what is there. At the end of the series you will also find 3D floor plans of both levels.',
    galeriaMind: 'All',
    galeriaSzuresCimke: 'Filter photos',
    cimkeFotok: (mi, n) => mi + ' — ' + n + ' photos in the gallery',
    arakTelMegjegyzes: 'The winter season runs from 1 December to the end of February and includes Christmas and New Year — at the same rate as the summer high season.',
    galeriaCimkeSzuro: (mi) => 'Just these: ' + mi,
    fotoNagyitas: 'Enlarge',

    foglalasFolott: 'Booking',
    foglalasCim: 'Let us find your dates.',
    lepes1: 'Dates and guests',
    lepes2: 'Your details',
    lepes3: 'Review',

    mezoIdopont: 'Dates',
    mezoErkezes: 'Arrival',
    mezoTavozas: 'Departure',
    mezoFelnott: 'Adults',
    mezoGyerek: 'Children',
    mezoFekvohelyek: 'Sleeping arrangements',
    mezoExtrak: 'Extras',
    mezoNev: 'Name',
    mezoEmail: 'Email',
    mezoTelefon: 'Phone number',
    mezoMegjegyzes: 'Note',

    sugoTurnus: (n) => 'exactly ' + n + ' nights, Saturday to Saturday',
    sugoMinEj: (n) => 'bookable from ' + n + ' nights',
    sugoFelnott: 'Aged 18 and over — tourist tax applies to them.',
    sugoGyerek: 'Under 18, exempt from tourist tax.',
    sugoExtrak: 'You can change these any time until we reply.',
    sugoTelefon: 'Only if we need to call you back.',
    sugoMegjegyzes: 'Allergies, early arrival, anything else.',
    mintaNev: 'Anna Smith',
    mintaMegjegyzes: 'We are coming with two small children and would bring our dog.',

    fekvohelyBevezeto: (alap, pot) => ['Regular sleeping places for ' + alap + ' guests', ' in the two upstairs bedrooms, and the living-room sofa converts into a bed for ' + pot + ' more.'],
    kanapeCimke: 'Please make up the living-room sofa as a bed',
    kanapeKell: (n) => 'With ' + n + ' guests this is needed, so we have ticked it.',
    kanapeNemKell: 'If you do not need it, we leave it as a sofa.',
    gyerekagyCimke: 'Cot in the three-bed room',
    gyerekagyLeiras: 'Free of charge, and it does not count towards capacity.',
    etetoszekCimke: 'High chair',
    etetoszekLeiras: 'Free of charge — let us know in advance and we will set it out.',

    naptarSugo: 'Click your arrival day, then your departure day',
    naptarSzabad: 'free',
    naptarFoglalt: 'booked',
    naptarKivalasztva: 'selected',
    naptarNapCimke: (nap, foglalt) => nap + (foglalt ? ' — booked' : ''),
    elozoHonap: 'Previous month',
    kovetkezoHonap: 'Next month',

    altCim: 'The house is free on these dates',
    altHaNemJo: 'If none of these work, write or call — a booking does sometimes free up.',
    altNincs: 'We could not find a free period of this length in the coming months. Write to us and we will see what can be done.',
    altUgyanaznap: 'on the same day',
    altKesobb: (e) => e + ' later',
    altKorabban: (e) => e + ' earlier',
    altNap: (n) => n + (n === 1 ? ' day' : ' days'),
    altHet: (n) => n + (n === 1 ? ' week' : ' weeks'),

    osszValasztottIdopont: 'Choose your dates',
    osszIfa: 'Tourist tax',
    osszFoglaloMost: 'Deposit due now',
    osszSzallasdij: 'Accommodation',
    osszKaucio: 'Security deposit',
    osszAllapot: 'Status',
    osszVendegek: 'Guests',

    feltFoglalo: 'Deposit',
    feltFoglaloOsszeg: (osszeg) => osszeg + ' by bank transfer — this confirms the booking',
    feltFoglaloSzazalek: (szazalek) => szazalek + '% of the accommodation price by bank transfer — this confirms the booking',
    feltHatralek: 'Balance',
    feltHatralekSzoveg: 'Transferred 14 days before arrival, or paid in cash on arrival',
    feltIfaSzoveg: (osszeg) => osszeg + ' per person per night, aged 18 and over — cash on arrival',
    feltKaucioSzoveg: (osszeg) => osszeg + ' cash on arrival, returned on departure',
    feltLemondas: 'Cancellation',
    feltLemondasSzoveg: (nap) => 'Cancel more than ' + nap + ' days before arrival and we refund the deposit',
    feltTeljesHazirend: 'Full house rules',

    attekIdopont: 'Dates',
    attekFekvohelyek: 'Sleeping arrangements',
    attekHaloszobakban: (n) => n + ' guests in the bedrooms',
    attekKanape: 'living-room sofa made up as a bed',
    attekCsakHalo: 'bedrooms only',
    attekGyerekagy: 'cot',
    attekEtetoszek: 'high chair',
    attekNemAdtadMeg: 'not provided',
    mitTortenik: 'What happens next?',
    mitTortenikSzoveg: (foglalo) => 'We check the calendar and reply by email within 24 hours. Once we confirm, transferring the ' + foglalo + ' deposit makes the booking final.',
    elfogadom: (link) => ['I accept the ', link],
    elfogadomLink: 'house rules',
    kuldes: 'Send request',

    hibaDatum: 'Please choose an arrival and a departure day.',
    hibaNev: 'Please give your name so we know who we are writing to.',
    hibaEmail: 'Please give a valid email address.',
    hibaFeltetel: 'We cannot record the request without accepting the house rules.',

    kesz: 'We have your request',
    keszSzoveg: (idoszak, vendegek, email) => idoszak + ', ' + vendegek + '. We have sent a confirmation to ' + email + '.',
    keszMasodik: (foglalo) => 'We will write within 24 hours to say whether the house is free. After our confirmation, transferring the ' + foglalo + ' deposit makes the booking final.',
    keszRogzitve: 'Request recorded',
    keszAzonosito: (a) => 'Reference: ' + a,
    keszLekerdezes: (link) => ['With this reference and your email address you can check your booking any time on the ', link, ' page — you can also cancel there.'],
    keszFooldal: 'Back to the home page',
    keszFoglalasom: 'My booking',

    lekFolott: 'My booking',
    lekCim: 'See where your booking stands.',
    lekBevezeto: (a, e) => ['You received the reference by email after sending the request. It only works together with your email address, so both are needed. (In this demo, try: ', a, ' and ', e, '.)'],
    lekAzonosito: 'Booking reference',
    lekEmail: 'Email address',
    lekGomb: 'Find my booking',
    lekNincs: 'Not found',
    lekNincsSzoveg: (tel) => 'We have no booking with this reference and email address. Check the confirmation email, or call us: ' + tel + '.',

    allapotFuggoben: 'Pending',
    allapotVisszaigazolt: 'Confirmed',
    allapotLemondott: 'Cancelled',

    lemIngyenes: 'Free cancellation',
    lemIngyenesSzoveg: (datum) => 'Free to cancel until midnight on ' + datum + '; we refund the deposit.',
    lemNemIngyenes: 'The deposit is no longer refundable',
    lemNemIngyenesSzoveg: (datum) => 'The free cancellation deadline (' + datum + ') has passed. You can still cancel, but we are not able to refund the deposit.',
    lemMar: 'This booking has been cancelled',
    lemMarSzoveg: 'If you would like to come after all, just start a new booking — you are welcome.',
    lemModositas: 'I want to change it — I will call',
    lemGomb: 'Cancel booking',
    lemBiztos: 'Cancel for sure?',
    lemBiztosSzoveg: (idoszak) => idoszak + ' — we will cancel this booking and the house becomes bookable again.',
    lemVisszajar: (osszeg) => 'Deposit refunded: ' + osszeg,
    lemNemJar: 'The deposit is not refundable',
    lemIgen: 'Yes, cancel it',
    kaucioVisszatero: 'Waived for returning guests',
    kaucioErkezeskor: (osszeg) => osszeg + ' on arrival, returned on departure',
    ifaErkezeskor: (osszeg) => osszeg + ' — cash on arrival',

    hazirendFolott: 'House rules',
    hazirendCim: 'What we agree on.',
    hazirendBevezeto: 'Short, and with no catches. The deposit and cancellation terms also appear during booking.',

    kapcsolatFolott: 'Contact',
    kapcsolatCim: 'Just ask.',
    kapcsolatElerhetoseg: 'Get in touch',
    kapcsolatUtvonal: 'Route on the map',
    kapcsolatOdajutas: 'Getting here',

    lablecBevezeto: (alap, pot) => 'A holiday house on the Kákafok backwater in Békésszentandrás. Two bedrooms, a large garden, a pool and a private jetty — for ' + alap + ' + ' + pot + ' guests, rented as a whole.',
    lablecHaz: 'The house',
    lablecHazFelszereltseg: 'The house and facilities',
    lablecArak: 'Prices and terms',
    lablecKapcsolat: 'Contact',
    lablecJoTudni: 'Good to know',
    lablecLemondas: 'Cancellation terms',
    lablecGyik: 'Frequent questions',
    lablecDemo: 'Reset demo data',

    /* --- Error messages --- */
    napNevek: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    hibaMult: 'That date is in the past.',
    hibaLetszam: (max) => 'We can host at most ' + max + ' guests.',
    hibaRosszIdoszak: 'The departure date must be later than the arrival date.',
    hibaMinEj: (n) => 'In this period we can take bookings of at least ' + n + ' nights.',
    hibaTurnus: (n, nap) => 'In this period the house goes in fixed weeks of ' + n + ' nights, with changeover on ' + nap + '.',
    hibaFoglalt: 'Sorry — these dates are already taken.',
    hibaAltalanos: 'That did not work just now. Please try again.',
    /* --- Booking (C) --- */
    foglalasMegNemKell: 'This is only a request — nothing is payable until we reply.',
    hibaCim: 'Not sent',
    kanapeFigyelmeztetes: (n) => 'With ' + n + ' guests we make up the living-room sofa as a bed.',
    mezoFizetes: 'Paying the balance',
    sugoFizetes: 'We always ask for the deposit by bank transfer.',
    fizetesAtutalas: 'By bank transfer, 14 days before arrival',
    fizetesKeszpenz: 'In cash on the day of arrival',
    fizetesKeszpenzLeiras: 'The tourist tax and the security deposit are in cash either way.',
    hirlevel: 'Let us know about special weekends',
    nincsExtra: 'none',
    attekMegjegyzesed: 'Your note:',
    elfogadomKetto: (a, b) => ['I accept the ', a, ' and the ', b],
    elfogadomAdatLink: 'privacy notice',
    kuldesFolyamatban: 'Sending…',
    keszKaucio: (osszeg) => 'On arrival, ' + osszeg + ' security deposit and the tourist tax in cash.',
    allapotLezart: 'Completed',
    lekAzonositoMinta: 'RV-2026-0714',
    lekSugo: (minta) => ['You received the reference by email after sending the request — it looks like this: ', minta, '. It only works together with your email address, so both are needed.'],
    lekKeresFolyamatban: 'Searching…',
    lemondasFolyamatban: 'Cancelling…',
    lemondasKesz: 'Done',
    lemondasKeszVisszajar: 'We have cancelled the booking and will refund the deposit.',
    lemondasKeszSima: 'We have cancelled the booking.',
    lemUjFoglalas: (link) => ['If you would like to come after all, just start a ', link, ' — you are welcome.'],
    lemUjFoglalasLink: 'new booking',
    fizetesAllapot: { unpaid: 'Deposit not received yet', deposit_paid: 'Deposit received', paid: 'Paid in full', refunded: 'Deposit refunded' },
    reszletekHazirend: (link) => ['The detailed terms are in the ', link, '.'],
    reszletekHazirendLink: 'house rules',

    hibaNemMondhatoLe: 'This booking can no longer be cancelled here — please give us a call.',

  

    /* --- A többoldalas változathoz: környék, kapcsolat, adatkezelés, impresszum --- */
    reszletek: 'Details',
    haloPlusz: (n) => '+' + n + (n === 1 ? ' guest' : ' guests'),
    kornyekGomb: 'What there is to do',
    zaroNaptar: 'We keep the calendar ourselves and reply within 24 hours.',
    gyikIrj: (link) => ['If something is missing, ', link, '.'],
    gyikIrjLink: 'just write to us',
    vendegekSzama: 'Number of guests',
    savSzabad: (ej, osszeg) => 'Free — ' + ej + (ej === 1 ? ' night' : ' nights') + ', ' + osszeg + ' in total',
    kornyekHeroFelirat: 'The Kákafok backwater at the end of the garden — this is where the kayaks set off.',
    kornyekOldalCim: 'The backwater, the dyke and the area around.',
    kornyekOldalLead: 'Nothing is far away, and nothing needs arranging in advance. We live here, so ask us any time.',
    holFolott: 'Finding us',
    holCim: 'Where the house is.',
    holP1: 'In Békésszentandrás, on the bank of the Kákafok backwater, inside a nature reserve. 150 km from Budapest, roughly two hours by car. By train you can come as far as Szarvas, and we will pick you up from there.',
    holP2: 'No motorboats run on the backwater, so the water stays quiet. A flat path runs along the dyke towards Szarvas and Gyomaendrőd — there are three bicycles at the house.',
    utvonaltervezes: 'Get directions',
    kerdesemVan: 'I have a question',
    mikorJonnetek: 'When would you come?',
    naptarBevezeto: 'We keep the calendar ourselves — see when the house is free.',
    kapcsolatLead: 'We live here and hand over the keys ourselves. If anything is unclear before booking, a phone call is enough.',
    mezoUzenet: 'How can we help?',
    mintaEmail: 'anna@example.com',
    mintaUzenet: 'Five of us would come in July, with two small children…',
    hibaUzenetSzoveg: 'Write a few words about how we can help.',
    hibaAdatkezeles: 'We cannot send the message without accepting the privacy notice.',
    adatkezelesElfogadom: 'I have read the privacy notice',
    uzenetKeszCim: 'We have your message',
    uzenetKeszSzoveg: 'We reply within 24 hours.',
    uzenetHiba: 'Sending did not work just now. Please try again, or give us a call.',
    uzenetElkuldve: 'Sent',
    uzenetElkuldveSzoveg: 'We will check the calendar and write to the address you gave within 24 hours.',
    uzenetKuldes: 'Send message',
    terkepCim: 'The house on the map',
    nemetorszagbol: '(from Germany)',
    zartUdvar: 'Closed yard',
    szabadIdopontok: 'See free dates',
    impresszumNtak: (szam) => 'Private accommodation · NTAK registration number: ' + szam,
    adatBlokkok: (email) => [
      ['What data we handle', [
        'When booking: name, email address, phone number, arrival and departure dates, number of guests and your note.',
        'On arrival, as required by law, the details of your identity documents, because of the reporting obligation towards the Hungarian tourism data centre (NTAK).',
      ]],
      ['Why we handle it', [
        'To confirm and fulfil the booking, and for invoicing.',
        'To meet the statutory reporting obligation (NTAK).',
      ]],
      ['How long we keep it', [
        'Booking-related data for as long as accounting rules require.',
        'Enquiries that did not turn into a booking for at most one year.',
      ]],
      ['Who we pass it to', [
        'To nobody, apart from the reporting to the authorities required by law.',
        'This website uses no tracking or advertising cookies.',
      ]],
      ['Your rights', [
        'You can ask for a copy of the data we hold about you, or for its correction or deletion.',
        'Write to ' + email + ' and we will answer within 30 days.',
      ]],
    ],
    adatMegjegyzes: 'This notice is part of the demo; before going live it is worth having a lawyer review it.',
    nincsOldalCim: 'This page does not exist.',
    nincsOldalSzoveg: 'We may have mistyped the link. The house, the rooms and booking are all reachable from here.',
    hazOsszesKep: (n) => 'All ' + n + ' photos',
    hazHaloBevezeto: (alap, max) => 'The two upstairs bedrooms give you the ' + alap + ' standard beds. We make up the living-room sofa on request for two more — house rules allow at most ' + max + ' of you in the house.',
    joTudniCim: 'Worth a quick read before you book.',
    galeriaHazAlt: 'The Riverside holiday house',
    fotoMegnyitasa: (nev) => nev + ' — open photo',
    galeriaTovabbiFoto: (n) => '+' + n + ' photos',
    fotoNagyitasa: (nev) => nev + ' — enlarge',
    kotottTurnus: 'Fixed week',
    arakTurnusMegjegyzes: 'In every period the minimum is three nights, starting on any day. Summer is no exception.',
    feltetelekFolott: 'Terms',
    feltetelekCim: 'Deposit, security deposit, cancellation.',
    fizetesHogyanCim: 'How payment works',
    fizetesLepesek: [
      'You send the booking request, and we answer within 24 hours.',
      'Once we confirm, you transfer the deposit — that is what makes the booking live.',
      'The balance by transfer 14 days before arrival, or in cash when you get here.',
      'On arrival, the tourist tax and the security deposit in cash.',
    ],
    teljesLista: 'See the full list',
    kerdesVan: 'Got a question?',
    kerdesVanSzoveg: 'You can call us any time of day. We take any complaint seriously and sort it out on the spot wherever we can.',
    hazirendElfogadva: 'By booking the house you accept these rules.',
  },
};

/** A támogatott nyelvek, a fejléc kapcsolójának sorrendjében. */
const NYELVEK = ['hu', 'de', 'en'];

/**
 * Az adott nyelv szövegei. Ha egy kulcs hiányzik a német vagy angol
 * változatból, a magyar ugrik be helyette — így egy félbehagyott
 * fordítástól még nem lesz üres az oldal.
 */
function szoveg(nyelv) {
  const alap = SZOVEG.hu;
  const valasztott = SZOVEG[nyelv] || alap;
  return new Proxy(valasztott, {
    get: (cel, kulcs) => (kulcs in cel ? cel[kulcs] : alap[kulcs]),
  });
}

/* ============================================================
   ÚTVONALAK

   Minden nyelvnek saját címei vannak, hogy a link olvasható legyen
   annak is, aki azon a nyelven nézi:

     #/hu/arak      #/de/preise      #/en/prices

   A bal oldali kulcs belső név (ezt használja a kód), a jobb oldali
   a címsorban megjelenő szó. Nyelvváltáskor a rendszer a kulcs
   alapján megkeresi a másik nyelv megfelelő címét, így ugyanazon az
   oldalon maradsz.
   ============================================================ */

const UTVONALAK = {
  hu: { fooldal: '', haz: 'a-haz', arak: 'arak', galeria: 'galeria', kornyek: 'kornyek', foglalas: 'foglalas', foglalasom: 'foglalasom', hazirend: 'hazirend', kapcsolat: 'kapcsolat', adatkezeles: 'adatkezeles', impresszum: 'impresszum' },
  de: { fooldal: '', haz: 'das-haus', arak: 'preise', galeria: 'galerie', kornyek: 'umgebung', foglalas: 'buchen', foglalasom: 'meine-buchung', hazirend: 'hausordnung', kapcsolat: 'kontakt', adatkezeles: 'datenschutz', impresszum: 'impressum' },
  en: { fooldal: '', haz: 'the-house', arak: 'prices', galeria: 'gallery', kornyek: 'around-here', foglalas: 'book', foglalasom: 'my-booking', hazirend: 'house-rules', kapcsolat: 'contact', adatkezeles: 'privacy', impresszum: 'imprint' },
};

/** Egy oldal címe az adott nyelven: ut('de','arak') → '/de/preise' */
function ut(nyelv, oldalKulcs) {
  const szo = (UTVONALAK[nyelv] || UTVONALAK.hu)[oldalKulcs] ?? '';
  return '/' + nyelv + (szo ? '/' + szo : '');
}

/** A címsorból visszafejti a nyelvet és az oldalt.
    Bármelyik nyelv címszavát elfogadja, így egy régi link is működik. */
function utvonalBol(hash) {
  const reszek = String(hash || '').replace(/^#\/?/, '').split('/').filter(Boolean);
  const nyelv = NYELVEK.includes(reszek[0]) ? reszek[0] : null;
  const szo = (nyelv ? reszek[1] : reszek[0]) || '';
  if (!szo) return { nyelv, oldal: 'fooldal' };

  for (const ny of NYELVEK) {
    for (const [kulcs, ertek] of Object.entries(UTVONALAK[ny])) {
      if (ertek && ertek === szo) return { nyelv, oldal: kulcs };
    }
  }
  return { nyelv, oldal: 'fooldal' };
}

/** A böngésző nyelve alapján az első ajánlat. Ha nem ismerjük fel,
    marad a magyar. A választást a látogató bármikor felülírhatja. */
function bongeszoNyelve() {
  const lista = (navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language || 'hu']);
  for (const nyelvKod of lista) {
    const rovid = String(nyelvKod).slice(0, 2).toLowerCase();
    if (NYELVEK.includes(rovid)) return rovid;
  }
  return 'hu';
}
